# Generated by Django 5.2.8 on 2025-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=400, verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-published_at'],
            },
        ),
    ]
